users:
  admin:
    username_key: "ADMIN_USERNAME"
    password_key: "ADMIN_PASSWORD"

secret:
  password_key: "SECRET_PASSWORD"

employees:
  nitin:
    username_key: "NITIN_USERNAME"
    password_key: "NITIN_PASSWORD"

  anil:
    username_key: "ANIL_USERNAME"
    password_key: "ANIL_PASSWORD"

  neha:
    username_key: "NEHA_USERNAME"
    password_key: "NEHA_PASSWORD"

  shwetabh:
    username_key: "SHWETABH_USERNAME"
    password_key: "SHWETABH_PASSWORD"

  praveen:
    username_key: "PRAVEEN_USERNAME"
    password_key: "PRAVEEN_PASSWORD"

  sunita:
    username_key: "SUNITA_USERNAME"
    password_key: "SUNITA_PASSWORD"
  shivanshu:
    username_key: "SHIVANSHU_USERNAME"
    password_key: "SHIVANSHU_PASSWORD"

groups:
  sales:
    - nitin
    - anil
    - neha
    - shwetabh
    - shivanshu


  recruiters:
    - praveen
    - sunita
